;;;; lem-yath -> Lem: a faithful port of the "lem-yath" Emacs configuration to Lem.
;;;; The nix-built Lem image already contains the editor systems referenced by
;;;; these sources.  Do not list them as ASDF dependencies: doing so makes ASDF
;;;; try to rebuild bundled extensions inside the immutable Nix store.

(defsystem "lem-yath"
  :description "Port of yanni's Emacs (lem-yath) configuration to Lem."
  :author "yanni <yathxyz@gmail.com>"
  :license "MIT"
  :serial t
  :pathname "src/"
  :components ((:file "package")
               (:file "base")
               (:file "workspace")
               (:file "direnv")
               (:file "sops")
               (:file "editing")
               (:file "cursor-state")
               (:file "vi")
               (:file "terminal")
               (:file "avy")
               (:file "structural")
               (:file "electric-pair")
               (:file "completion")
               (:file "annotations")
               (:file "help")
               (:file "orderless")
               (:file "auto-completion")
               (:file "actions")
               (:file "snippets")
               (:file "lsp-snippets")
               (:file "csharp-mode")
               (:file "tree-sitter")
               (:file "ide")
               (:file "editorconfig")
               (:file "formatting")
               (:file "git")
               (:file "project")
               (:file "lint")
               (:file "dap")
               (:file "jump-feedback")
               (:file "project-picker")
               (:file "workspace-symbol")
               (:file "project-outline")
               (:module "org"
                :serial t
                :components ((:file "parser")
                             (:file "folding")
                             (:file "mode")
                             (:file "commands")
                             (:file "structure")
                             (:file "element-navigation")
                             (:file "text-objects")))
               (:file "roam")
               (:file "notes")
               (:file "roam-capture")
               (:file "dirvish")
               (:file "find-name")
               (:file "buffer-list")
               (:file "tools")
               (:file "lisp-eval")
               (:file "llm")
               (:file "indent-guides")
               (:file "theme")
               (:file "centered-view")
               (:file "window-history")
               (:file "ui")
               (:module "apps"
                :components ((:file "agenda")
                             (:file "agenda-archive")
                             (:file "agenda-refile")
                             (:file "agenda-clock")
                             (:file "citar")
                             (:file "devdocs")
                             (:file "elfeed")
                             (:file "notmuch")
                             (:file "pg")
                             (:file "salta")
                             (:file "timemachine")
                             (:file "llm-cli")
                             (:file "llm-presets")
                             (:file "claude-code")))
               (:file "bookmarks")
               (:file "persistence")
               (:file "vundo")
               (:static-file "compilation-guardian.py")
               (:file "compilation")
               (:file "prefix-help")
               (:file "keybindings")))
